export const experiencesContent = [
  {
    title: "Full-stack Web3 Developer",
    company: "Blessed",
    period: "03/2024 - 02/2025",
    description: "Continuation of license.rocks GmbH project",
    tech: ["NestJs", "Next.js", "Solidity", "Cairo", "AWS", "CI/CD"],
    achievements: [
      "Transitioned from Frontend to Full-stack Web3 Developer, showcasing adaptability and commitment to rapid skill acquisition",
      "Architected and implemented scalable backend infrastructure for Web3 ticketing platform",
      "Migrated classic Node.js API to NestJs, achieving 80% improvement in endpoint performance",
      "Optimized on-chain interactions on frontend, resulting in 50% increase in speed",
      "Designed and deployed smart contracts using Solidity and Cairo",
      "Conducted research on cutting-edge Web3 technologies",
      "Created comprehensive technical documentation for system maintainability",
    ],
  },
  {
    title: "Frontend Web3 Developer",
    company: "license.rocks GmbH",
    period: "06/2023 - 03/2024",
    description: "NFT-based digital licensing solutions for intellectual property protection",
    tech: ["Next.js", "Node.js", "Web3 libraries", "AWS S3", "CI/CD"],
    achievements: [
      "Designed and implemented NFT-based digital licensing solutions for enhanced IP protection",
      "Developed and deployed 5+ automated NFT storefronts, streamlining maintenance processes",
      "Integrated robust APIs using Node.js for seamless functionality and scalability",
      "Collaborated directly with clients to deliver tailored technical solutions",
      "Advanced expertise in Web3 technologies and backend development",
    ],
  },
  {
    title: "Frontend Web3 Developer",
    company: "Fullstak sp. z o.o.",
    period: "10/2022 - 06/2023",
    description: "Web3 application development with modern frontend technologies",
    tech: ["React", "Next.js", "Web3 libraries", "Tailwind", "Redux"],
    achievements: [
      "Architected advanced web applications with Web3 integrations",
      "Designed responsive user interfaces using Next.js for optimal cross-device experience",
      "Created complex animations enhancing user interaction and application appeal",
      "Integrated core Web3 functionalities including wallet connections",
      "Gained practical knowledge of blockchain technologies and dApps",
    ],
  },
  {
    title: "Frontend Web Developer",
    company: "Self Employed",
    period: "04/2021 - 10/2022",
    description: "Freelance web development for local businesses",
    tech: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    achievements: [
      "Designed responsive websites for local businesses with engaging user experiences",
      "Implemented SEO best practices, improving search engine rankings",
      "Optimized website performance through efficient coding practices",
      "Collaborated with clients to translate requirements into functional solutions",
      "Developed key professional skills in project management and client communication",
    ],
  },
]